server:
    port: 3002
spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/meta_stock
        username: root
        password: root
        driver-class-name: org.postgresql.Driver
    jpa:
        show-sql: true
    rabbitmq:
        host: localhost
        port: 5672
        username: rabbitmq
        password: 123456aA@
    devtools:
        restart:
            enabled: true
        livereload:
            enabled: true
