server:
    port: 3002
spring:
    profiles:
        active: dev
    application:
        name: stock-api
    jpa:
        hibernate:
            ddl-auto: none
            naming:
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        properties:
            hibernate:
                naming:
                    physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    rabbitmq:
        listener:
            simple:
                concurrency: 3
                max-concurrency: 10
