# Gradle Version Catalog
# https://docs.gradle.org/current/userguide/platforms.html#sub::toml-dependencies-format

[versions]
# Kotlin
kotlin="2.0.21"
# Spring
springBoot = "3.3.4"
springDependencyManagement = "1.1.6"

# Core Libraries
rxjava = "3.1.9"
retrofit = "2.11.0"
okhttp = "4.12.0"
jackson = "2.18.1"
jsonpath = "2.7.0"

# Development Tools
lombok = "1.18.34"
mapstruct = "1.5.5.Final"
lombok-mapstruct-binding = "0.2.0"

# Logging
slf4j = "2.0.16"
logback = "1.5.12"
janino = "3.1.12"
logstash_logback_version = "8.0"
# Documentation
springdoc = "2.6.0"

# Utilities
dotenv = "5.2.2"
spotless = "7.0.0.BETA4"

[plugins]
spring-boot = { id = "org.springframework.boot", version.ref = "springBoot" }
spring-dependency = { id = "io.spring.dependency-management", version.ref = "springDependencyManagement" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-spring = { id = "org.jetbrains.kotlin.plugin.spring", version.ref = "kotlin" }
kotlin-jpa = { id = "org.jetbrains.kotlin.plugin.jpa", version.ref = "kotlin" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }

[libraries]
# Kotlin
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin" }
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }

# Reactive & Network Libraries
rxjava = { group = "io.reactivex.rxjava3", name = "rxjava", version.ref = "rxjava" }
retrofit-core = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
retrofit-converter-gson = { group = "com.squareup.retrofit2", name = "converter-gson", version.ref = "retrofit" }
retrofit-adapter-rxjava3 = { group = "com.squareup.retrofit2", name = "adapter-rxjava3", version.ref = "retrofit" }
okhttp-logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttp" }

# JSON Processing
jackson-annotations = { group = "com.fasterxml.jackson.core", name = "jackson-annotations", version.ref = "jackson" }
jackson-module-kotlin = { module = "com.fasterxml.jackson.module:jackson-module-kotlin", version.ref = "jackson" }
jsonpath = { group = "com.jayway.jsonpath", name = "json-path", version.ref = "jsonpath" }

# Development Tools
lombok = { group = "org.projectlombok", name = "lombok", version.ref = "lombok" }
mapstruct = { group = "org.mapstruct", name = "mapstruct", version.ref = "mapstruct" }
mapstruct-processor = { group = "org.mapstruct", name = "mapstruct-processor", version.ref = "mapstruct" }
lombok-mapstruct-binding = { group = "org.projectlombok", name = "lombok-mapstruct-binding", version.ref = "lombok-mapstruct-binding" }

# Logging Stack
slf4j-api = { group = "org.slf4j", name = "slf4j-api", version.ref = "slf4j" }
logback-classic = { group = "ch.qos.logback", name = "logback-classic", version.ref = "logback" }
janino = { group = "org.codehaus.janino", name = "janino", version.ref = "janino" }
logstash-logback = { module = "net.logstash.logback:logstash-logback-encoder", version.ref = "logstash_logback_version" }

# API Documentation
springdoc-openapi-starter = { group = "org.springdoc", name = "springdoc-openapi-starter-webmvc-ui", version.ref = "springdoc" }

# Utilities
dotenv = { group = "io.github.cdimascio", name = "java-dotenv", version.ref = "dotenv" }

[bundles]
retrofit = ["retrofit-core", "retrofit-converter-gson", "retrofit-adapter-rxjava3", "okhttp-logging-interceptor"]
logging = ["slf4j-api", "logback-classic", "logstash-logback", "janino"]