# Gradle Version Catalog
# https://docs.gradle.org/current/userguide/platforms.html#sub::toml-dependencies-format

[versions]
# Spring
springBoot = "3.3.4"
springDependencyManagement = "1.1.6"

# Core Libraries
rxjava = "3.1.9"
retrofit = "2.11.0"
jackson = "2.18.1"

# Development Tools
lombok = "1.18.34"
mapstruct = "1.5.5.Final"
lombok-mapstruct-binding = "0.2.0"

# Logging
slf4j = "2.0.16"
logback = "1.5.12"
janino = "3.1.12"

# Documentation
springdoc = "2.6.0"

# Utilities
dotenv = "5.2.2"
spotless = "7.0.0.BETA4"

[plugins]
spring-boot = { id = "org.springframework.boot", version.ref = "springBoot" }
spring-dependency = { id = "io.spring.dependency-management", version.ref = "springDependencyManagement" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }

[libraries]
# Reactive & Network Libraries
rxjava = { group = "io.reactivex.rxjava3", name = "rxjava", version.ref = "rxjava" }
retrofit-core = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
retrofit-converter-gson = { group = "com.squareup.retrofit2", name = "converter-gson", version.ref = "retrofit" }
retrofit-adapter-rxjava3 = { group = "com.squareup.retrofit2", name = "adapter-rxjava3", version.ref = "retrofit" }

# JSON Processing
jackson-annotations = { group = "com.fasterxml.jackson.core", name = "jackson-annotations", version.ref = "jackson" }

# Development Tools
lombok = { group = "org.projectlombok", name = "lombok", version.ref = "lombok" }
mapstruct = { group = "org.mapstruct", name = "mapstruct", version.ref = "mapstruct" }
mapstruct-processor = { group = "org.mapstruct", name = "mapstruct-processor", version.ref = "mapstruct" }
lombok-mapstruct-binding = { group = "org.projectlombok", name = "lombok-mapstruct-binding", version.ref = "lombok-mapstruct-binding" }

# Logging Stack
slf4j-api = { group = "org.slf4j", name = "slf4j-api", version.ref = "slf4j" }
logback-classic = { group = "ch.qos.logback", name = "logback-classic", version.ref = "logback" }
janino = { group = "org.codehaus.janino", name = "janino", version.ref = "janino" }

# API Documentation
springdoc-openapi-starter = { group = "org.springdoc", name = "springdoc-openapi-starter-webmvc-ui", version.ref = "springdoc" }

# Utilities
dotenv = { group = "io.github.cdimascio", name = "java-dotenv", version.ref = "dotenv" }

[bundles]
retrofit = ["retrofit-core", "retrofit-converter-gson", "retrofit-adapter-rxjava3"]
logging = ["slf4j-api", "logback-classic", "janino"]