version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node_prisma_db
    volumes:
      - ./prisma:/app/prisma
      - ./package.json:/app/package.json
    environment:
      DATABASE_URL: postgresql://root:root@host.docker.internal:5432/java_demo?schema=public&connection_limit=7
    command: npx prisma migrate dev